### ISSUE TITLE
File System Commands are Always Case Sensitive

### ISSUE THREAD

**Issue by moloch--** [BishopFox/sliver#1017]
https://twitter.com/r0pchain/status/1597938215587303425

**Comment by moloch--** [comment]
Bug is in upstream Go https://github.com/golang/go/issues/5441

**Comment by rkervella** [comment]
Only occurs when a filter is used, which results in a call to `filepath.Match()`, which respects the case of the filter provided. Case sensitivity is a filesystem feature, not an OS feature, which explains why this issue probably won't be fixed in upstream `filepath.Match` (because the fix would need to check recursively the filesystem of each directory to determine whether it's case sensitive or not, and there's not solution to do that afaik).

The acceptable fix would be to consider that when the implant runs on Windows, we assume any mounted file system is case insensitive and call `strings.ToLower` on both the filter and path passed by the operator. This will require a bit of refactoring to extract the filtering logic so this hack is only applied on a `go:build +windows` constraints.

The only other part where we apply glob matching is in the download handler, which would need to be taken care of as well.
