### ISSUE TITLE
Interactive shell does not properly exit

### ISSUE THREAD

**Issue by tophertimzen** [BishopFox/sliver#105]
**Describe the bug**
When you go into an interactive shell session on a sliver and then attempt to exit it with `exit`, the shell just hangs and the `sliver-client` hangs as well.

**To Reproduce**
1. Generate an implant
2. Run implant on a Linux platform
3. Start an interactive shell session
4. Run `exit`

This was also done on a multiplayer sliver instance. 

**Expected behavior**
Shell exits and you are returned to the sliver interactive CLI

**Desktop (please complete the following information):**
- VERSION="18.04.2 LTS (Bionic Beaver)"

**Comment by moloch--** [comment]
You must use EOF (ctrl+d) in addition to `exit`

**Comment by moloch--** [comment]
If anyone has suggestions on how to approach this problem I'm open to it, I wrestled with it for a while. The crux of the problem is we read the process's (server or client) `os.Stdin` but when the remote process exists there's no way to either 1) cancel the `read()` call, or 2) programatically send EOF.

**Comment by moloch--** [comment]
Relavent code: https://github.com/BishopFox/sliver/blob/master/client/command/shell.go#L112

**Comment by Matir** [comment]
FWIW, on current master, running `exit` in a shell results in the server and implant both panicking.

**Comment by rkervella** [comment]
@Matir do you have a stack trace for that? I made some changes recently, and I can't observe this behavior.
