### ISSUE TITLE
I can not connect operators

### ISSUE THREAD

**Issue by JasBs** [BishopFox/sliver#1082]
I downloaded the Linux sliver server on AWS EC2 instance, created a new operator with the public ip of the instance, turned on multiplayer, moved the config file to my kali vm and tried to connect the client using the config but it said: Connection to server failed context deadline exceeded. Maybe I did something wrong how can I make it connect and work?

**Comment by moloch--** [comment]
You've not configured the firewalls to allow the TCP/31337 traffic for the multiplayer connection. This is likely due to not configuring the AWS Security Group to allow this traffic (in AWS you need to configure the host based firewall _and_ the security group to allow traffic on a given port). 

Note that you'll need to configure the security group to allow any C2 traffic too.
