### ISSUE TITLE
Unable to kill wg job

### ISSUE THREAD

**Issue by r00t0v3rr1d3** [BishopFox/sliver#1192]
**Describe the bug**
Unable to kill wg job. It says killed, but shows still running. Then if you try again, it hangs forever.

**To Reproduce**
1. See picture

**Screenshots**
![sliver_wireguard_failed_jobkill](https://user-images.githubusercontent.com/8229583/230974611-4c038ab9-a8a2-41a9-88ad-0eaf79f648c7.png)

**Desktop (please complete the following information):**
 - OS: Kali Linux
 - Version v.1.5.36 release binary

**Additional context**

**Comment by RafBishopFox** [comment]
Good catch. Thanks for reporting this. I took a look, and I think we were calling the job done before we finishing tearing down the listener. I believe this is now fixed in commit f09efe9512f10c92f180ec83235004aeefc594c0

![image](https://user-images.githubusercontent.com/84349012/231157327-2810fb67-d034-4ff3-b4ce-a67014962c0b.png)

The listening socket is also closed when I run `netstat` / `ss`.
