### ISSUE TITLE
[Docker] Run Sliver server from writable CWD

### ISSUE THREAD

**Issue by moloch--** [BishopFox/sliver#132]
**Describe the bug**

Currently the Docker server process is run from a CWD that is not writable by the user the server process is executed as, which means that users must specify a `--save` location and by default builds will fail. Related to issue #130 

**Expected behavior**

Default build commands should work with the need to specify additional flags.

**Desktop (please complete the following information):**
 - OS: Docker/linux
 - Version v0.0.7 (master)

**Comment by khast3x** [comment]
Hello,

Fixed the CWD issue by adding:
```
RUN chown -R sliver:sliver /go/src/github.com/bishopfox/sliver
USER sliver
ENTRYPOINT [ "/opt/sliver-server" ]
```

I have since managed to run the implant successfully :tada:

It might be more elegant to test writing perms before generating binary and output to `/tmp` or something? Idk.  
In practical usage, running the C2 with docker is also done by mounting a volume so as to get the binary. Maybe use a default volume that is chowned correctly?

Cheers!

**Comment by moloch--** [comment]
There's a couple shortcomings of the current tests in that (1) they're execute as the `root` user, and (2) don't cover all use cases of the`generate` command. Changing the CWD is easy enough short-term but long-term I think we need to create better CI/CD integration tests.

**Comment by moloch--** [comment]
Fixed, but due to the increased code in the implant obfuscation process takes about 3 hours and 45mins on a `t2.xlarge` .... which is not ideal, but should be addressed once we have a better staged version.
