### ISSUE TITLE
Syntax for execute command is not intuititive

### ISSUE THREAD

**Issue by Matir** [BishopFox/sliver#145]
**Is your feature request related to a problem? Please describe.**
Running a remote command with arguments is rather painful because of necessity of specifying arguments with a flag and doing so first.  It would be nice to be able to do it in order like I would on a shell.

**Describe the solution you'd like**
`execute /bin/ls -al` becomes the same as `execute -o -a -al /bin/ls`

**Additional context**
I'm happy to send a PR that changes this somewhat if it would be welcomed.  :)

**Comment by moloch--** [comment]
We welcome all PRs!

**Comment by rkervella** [comment]
@Matir I totally agree. I rushed that one out of necessity a few months back, but it surely could benefit from a rework. You're more than welcome to submit a PR, otherwise I'll try to work on that when I get the chance.
You might have to put the args under quotation mark though, otherwise grumble will take it as flags for the command.
Something like `execute -o /bin/ls "-al"`.
There are other things that could be enhanced on the `execute` command, mostly the output handling.

**Comment by Matir** [comment]
Sorry for the silence, I've been swamped at work.  I'll be working on a PR for this soon, but @rkervella, I'm curious what you meant by "the output handling"?

**Comment by rkervella** [comment]
Right now we either run `cmd.Start()` or `cmd.Output()` to run the command, depending on the `-o` flag. As `Output()` is blocking, the sliver-client can timeout and we won't receive the output. It's ok as of now, but there's probably some room for improvement here.

**Comment by rkervella** [comment]
@Matir I have a fix incoming for this one in the grpc branch.

```
sliver (NOVEL_MISTER) > execute -o ls -l /home

[*] Output:
total 20
drwx------. 48 blah blah  4096 May  4 16:11 blah
drwx------.  2 root      root      16384 Apr 26 23:37 lost+found
```
I'll close this issue when it's pushed and merged in master.
