### ISSUE TITLE
QUESTION. How to run BOF Files with Coff-loader.

### ISSUE THREAD

**Issue by kamisw03** [BishopFox/sliver#1561]
I tried to run some .o files using the cof loader, however they do not work properly.
I followed the docs for importing the custom extension, and it does not work either.

is there a way to load .o extensions directly using coff-loader, or if I need to import the extension using `extensions.json`, how can I do it?
I tried, I created it properly based on a cna script, but it did not work, either.

the docs for this is kind of limited, so i would like to know if there is a way to do it.

this is an example of a BOF extension that i tried to include, but it fails and does not report any error, it just does not load it.

```
"name": "test",
  "version": "1.0.0",
  "command_name": "etw-test",
  "extension_author": "test",
  "original_author": "test",
  "repo_url": "test",
  "help": "start - stop ETW",
  "long_help": "",
  "depends_on": "coff-loader",
  "entrypoint": "go",
  "files": [
    {
      "os": "windows",
      "arch": "amd64",
      "path": "etw.x64.o"
    },
    {
      "os": "windows",
      "arch": "386",
      "path": "etw.x86.o"
    }
  ],
  "arguments": [
    {
      "name": "start-stop",
      "desc": "start or stop",
      "type": "wstring",
      "optional": false
    }
  ]
}
```

i am sure i did it correcly, do not know if i need any aditional change to be able to include it.
 this is the original CNA script

```
beacon_command_register(
"etw", 
"Start or stop ETW logging.", 
"etw stop - patch out EtwEventWrite in Ntdll.dll to prevent ETW-based logging.
etw start - patch back in EtwEventWrite in Ntdll.dll to restart ETW-based logging.");

alias etw {
	local('$barch $handle $data $args');

	if(size(@_) != 2)
	{
		berror($1, "Incorrect usage!");
		berror($1, beacon_command_detail("etw"));
		return;
	}

	if(($2 eq "start")||($2 eq "stop"))
	{
		# figure out the arch of this session
		$barch  = barch($1);
		
		# read in the right BOF file
		$handle = openf(script_resource("etw. $+ $barch $+ .o"));
		$data   = readb($handle, -1);
		closef($handle);

		# pack our arguments
		$args = bof_pack($1, "z", $2);
		
		# announce what we're doing
		btask($1, "Running ETW patching BOF (@ajpc500)");
		
		# execute it.
		beacon_inline_execute($1, $data, "go", $args);
	}else{
		berror($1, "Incorrect usage!");
		berror($1, beacon_command_detail("etw"));
		return;
	}
}
```
hope you can give me a better idea of how to work around those BOF, because i think there are many interesting ones that I want to include to my extensions.

**Comment by rkervella** [comment]
> is there a way to load .o extensions directly using coff-loader, or if I need to import the extension using extensions.json, how can I do it?

Yes, but it's tedious. `coff-loader` being an extension itself, it expects arguments being passed in a certain way. The arguments are packed using the same argument parser than the BOFs use (see [here](https://github.com/sliverarmory/COFFLoader/blob/main/COFFLoader.c#L182-L197)). These arguments are (in order):
- the name of the export to call in the COFF file
- the COFF file data itself
- the packed arguments for the BOF

As I said, this is tedious, hence why the `sliver-client` does that for you when you register a new extension. The `coff-loader` command in the client was never intended to be used directly, and afaik, there's no way to make it work properly due to how you need to pass arguments to it (I'll probably mask it in v1.6).

Now, what you want to do is to add your custom extension. To do so, you can either use `extension load` and `extension install`, or just drop your extension files in a new folder in `~/.sliver-client/extensions/YOUR_EXTENSION_NAME`. Be mindful that the `YOUR_EXTENSION_NAME` needs to match the command name in the manifest file (`extension.json`). So in your case, it should be named `etw-test`.
