### ISSUE TITLE
Valid go files are filtered out from the implant build folder

### ISSUE THREAD

**Issue by ejohn** [BishopFox/sliver#160]
**Describe the bug**
Go source code files with a name of the format `_foo.go` are removed from the final sliver implant build folder if they are not necessary for the implant to compile. This is fine and intended when `foo` is test or an OS/Arch name. However there are cases when this prevents legitimate files from being copied.

I ran into this issue while trying to import `github.com/miekg/dns` into the implant. This might be bad practice in go but the project has files like `_generate.go`, `_keygen.go` etc which are needed for the implant to compile.

**To Reproduce**
Add `github.com/miekg/dns` as a third party library to be used by the implant.

**Expected behavior**
Only test and OS/Arch files which mismatch with the intended config should be discarded.

**Desktop (please complete the following information):**
 - OS: Mac
 - Version v0.0.7

**Comment by rkervella** [comment]
If I recall correctly, we did this on purpose because there was an issue with the obfuscation process. @moloch-- would know better though.

**Comment by moloch--** [comment]
Yes, this is by design. You have to add the files to [`server/generate/srcfiles.go`](https://github.com/BishopFox/sliver/blob/master/server/generate/srcfiles.go), this is done because the obfuscation process will trip on certain go files that use CGO for example or architectures other than the one the build is targeting (files specific to other architectures will also be filtered out by the build process).

Add any specific files you want to `srcfiles.go` to have them included in the build. This of course isn't ideal but it's the best way we've found so far.

**Comment by moloch--** [comment]
Ah okay I see, you just want to filter out only-known architectures, this seems reasonable to me.
