### ISSUE TITLE
Implant very prune to crashing, downloads as one example

### ISSUE THREAD

**Issue by nf-works** [BishopFox/sliver#1818]
After reading loads of positive things about Sliver, I gave it a try for two days. Please do not get me wrong. We should all be really thankful your team put this out there for everyone free of charge, but to me, it doesn't seem to be something I am comfortable using in production in its current state, or I am doing something fundamentally wrong. Being it tasks that don't finish for unknown reasons or implants simply crashing again and again. The former isn't much of an issue. You just try again or work your way around it. Having your implant die after some hard work to get it on the target system is something you really do not want, though. I naturally thought it was related to my custom stager or something like that, but that is not the case.
I'll keep (or try to) the upper part of this report _relatively_ short and will add a few more experiments, thoughts, and questions at the bottom.
I first didn't bother too much before the crashes started, so I don't recall everything, unfortunately. One thing I can easily reproduce is crashes for downloads, which I will mainly focus on. I know there are a multitude of open, years old, download-related issues, but I think this is yet another one.

**Describe the bug**
I had implants die on all hosts I have worked with so far, which is three. I think it was mostly related to downloads. `cat` must have been among the offenders, too. To my knowledge, it is basically the same implementation from an implant's perspective, which would make sense.

If I recall correctly, the first crash happened when trying to download a roughly 8 MB small file or something similar. So it is not https://github.com/BishopFox/sliver/issues/730. I ran tests with bigger files on a different host with an implant. 150 MB, for instance, were not an issue. Really big files did not work. It is probably https://github.com/BishopFox/sliver/issues/730 / https://github.com/BishopFox/sliver/issues/695. I found one issue related to small files (https://github.com/BishopFox/sliver/issues/1033), but it reads like it is about client crashes.
So I think here comes another one.

Today I took the time to go through more and more open GitHub issues and retry with debug builds. A 250 MB file was successfully received from a host whose implant previously died without successfully transmitting the file. The implant still died right after. I cannot tell if it is the same error as when it died with success yesterday, or just another one.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa385e1]

goroutine 242 [running]:
github.com/bishopfox/sliver/implant/sliver/transports.wgBeacon.func5()
	/root/.sliver/slivers/linux/amd64/[BUILD]/src/github.com/bishopfox/sliver/implant/sliver/transports/beacon.go:207 +0x41
main.beaconMain.func1()
	/root/.sliver/slivers/linux/amd64/[BUILD]/src/github.com/bishopfox/sliver/sliver.go:245 +0x50
main.beaconMain(0xc00007a410, {0xc1c55f18ab6556bb, 0x25110c84c7, 0x1344d00})
	/root/.sliver/slivers/linux/amd64/[BUILD]/src/github.com/bishopfox/sliver/sliver.go:325 +0xff6
main.beaconMainLoop.func2()
	/root/.sliver/slivers/linux/amd64/[BUILD]/src/github.com/bishopfox/sliver/sliver.go:204 +0x76
created by main.beaconMainLoop
	/root/.sliver/slivers/linux/amd64/[BUILD]/src/github.com/bishopfox/sliver/sliver.go:202 +0x82a
```

**To Reproduce**
Just for the sake of filling out the entire template.
1. Build a beacon WireGuard implant (evasion turned on, some port configuration, amd64 for Linux, executable format)
2. Start your WireGuard listener with the ports configured in step 1
3. Start the implant on a host
4. Download a file I guess? (`download --timeout 600 [PATH]`)

**Expected behavior**
- Ideally, the file would be downloaded.
- In any case, the implant should never be lost.

**Sliver server (please complete the following information):**
 - OS: Debian (with Kicksecure)
 - Sliver version v1.5.42

**Additional context**
This would be my experiments, thoughts, and questions area.

_Experiments/observations/thoughts_
- **Timeouts**. Running the same command from the steps above without a timeout changes nothing I could point out. It keeps sending and receiving the file. According to the help page, it should default to a 60-second timeout. The file was received after roughly 3 minutes, which would exceed the ominous timeout by 2 minutes. More on that below. For the implant, it was business as usual. It died.
- **More on timeouts and on robustness compared to interactive sessions**. Running the command with a timeout again (600 seconds as above), but in an interactive session, it did stop after presumably 10 minutes. This made me think the timeout option is only for sessions, perhaps? Additionally, the implant did not die. I would have loved receiving the file, but the implant is much more important. Digging through more and more issues and comments, I again found more crucial information than I found anywhere else (such as help pages). https://github.com/BishopFox/sliver/issues/940#issuecomment-1275217828 suggests to me that it is indeed what I suspected, and even beyond that, it doesn't stop anything related to the executed command itself. Does it do anything other than give back the interactive session to the client? If not, it is more like a foreground execution timeout. I feel like `command timeout in seconds`, copied from one of the help pages, would be very misleading then. It is certainly not what the average user expects from a “command timeout”.
- **Unfinished tasks and more on interactive sessions working better**. Back to a different server, on which a mere 8 MB caused a crashing implant already, it simply did nothing today. It didn't crash, it didn't transmit the file successfully, and it didn't finish the task. That is probably one of these cases I mentioned in the first part of my little monologue. The implant lives, so it is not really bad. The second attempt was a success after 4 seconds. The third and fourth attempts ended (or never ended) like the first attempt. Nothing in the implant's debug output appeared to be useful at first glance. Again, trying it twice in an interactive session worked fine right away both times.

_Questions_
- Have I missed some proper documentation on what a “timeout” is? Does it do anything beyond giving back the interactive session to the client? If not, is it not more like a foreground execution/wait for result timeout?
- For at least one of the known downloads bugs/issues, fixes and updates have been worked on two and a half years ago. Unfortunately, none of them seem to have made it into a release. I feel like such clear known limitations in file download sizes should at the very least be prominently added to the help page for commands, potentially even require some kind of confirmation prompt? I only found out by losing implants and digging through years old issues. Would you be open for a PR adding that to the help page?
- Any ideas how to debug the tasks which just end up uncompleted?
- Are interactive sessions more robust than beacons, given above observations?
- Are there differences in robustness when it comes to different transports?
- Any tricks from someone more experience when it comes to using Sliver, potentially even daily in engagements? Surely it is being used and people must know their way around these issues. Related to a previous point, do people usually switch to sessions when actively engaging with a host and let it rest as a beacon when not actively tinkering with it, despite the impact on OPSEC?
- May I put bounties for community contributors or the Bishop Fox team themselves on certain issues/improvements to the benefit of everyone using Sliver? The first priority would be stability. If it does not work one way, it will work another or at a different try. But as I keep saying, a lost implant really is a dealbreaker if your persistence is not a simple cronjob giving you access again shortly.

**Comment by rkervella** [comment]
That's a lot to unpack so I'll try to be concise.

> We should all be really thankful your team put this out there for everyone free of charge, but to me, it doesn't seem to be something I am comfortable using in production in its current state

A small reminder that this is open source software, we only have so much free time, we're not paid (i.e., we're not allocated specific time) to work on Sliver and the amount of time we can spend on the project is largely subject to our professional workloads. We're not forcing anyone to use Sliver either :)

We've been working on a big revamp for about a year now (v1.6), but there's still no available release because there's still a few things to work on and fix.

As for the questions:

1. Have I missed some proper documentation on what a “timeout” is? Does it do anything beyond giving back the interactive session to the client? If not, is it not more like a foreground execution/wait for result timeout?

In terms of direct user experience, and command timing out will give back the hand to the operator in the CLI. On the server, if there's a time out on a RPC, we won't store or process the results of the task that was sent to the implant. The server might receive it, but the result will not be passed to the client afaik.

2.  For at least one of the known downloads bugs/issues, fixes and updates have been worked on two and a half years ago. Unfortunately, none of them seem to have made it into a release. I feel like such clear known limitations in file download sizes should at the very least be prominently added to the help page for commands, potentially even require some kind of confirmation prompt? I only found out by losing implants and digging through years old issues. Would you be open for a PR adding that to the help page?

See my comment above, we only have so much free time. I believe some work have been done in `master` to fix parts of that but I would need to double check. We're not against PR to the documentation to add a mention about known issues though.

3. Any ideas how to debug the tasks which just end up uncompleted?

I'd try to run the server and implant through a debugger. See [this page](https://sliver.sh/docs?name=Debugging) for more info.

4. Are interactive sessions more robust than beacons, given above observations?

Beacons are a more recent implementation, so there's more chances for things to break here.

5. Are there differences in robustness when it comes to different transports?

mTLS is probably the more robust, DNS probably the one with the most issues currently, the rest is in between. We're regularly using HTTP(S) without major issues.

6. Any tricks from someone more experience when it comes to using Sliver, potentially even daily in engagements? Surely it is being used and people must know their way around these issues. Related to a previous point, do people usually switch to sessions when actively engaging with a host and let it rest as a beacon when not actively tinkering with it, despite the impact on OPSEC?

Anything that uses the `tunnel` implementation (`shell`, `socks`, `portfwd` for example) is not 100% reliable. It works most of the time but still breaks some times depending on the transports used. Switching to sessions when needed to go interactive is the way to go imo, unless it's against your OPSEC threshold.

7. May I put bounties for community contributors or the Bishop Fox team themselves on certain issues/improvements to the benefit of everyone using Sliver? The first priority would be stability. If it does not work one way, it will work another or at a different try. But as I keep saying, a lost implant really is a dealbreaker if your persistence is not a simple cronjob giving you access again shortly.

Putting bounties for open issues would not necessarily speed up the development pace: we'd still have to review PRs which takes time we don't always have.

One thing I can recommend is that you try out the version from the `master` branch and see if it fixes some of the issues you had, and if it brings Sliver in a usable state for your use case. You'll probably encounter other issues, but there's a bunch of things that we fixed in the past year that did not make it to either a release or was backported to v1.5.X.
