### ISSUE TITLE
Missing documentation about TCP and SMB Pivots

### ISSUE THREAD

**Issue by Ilan-sec** [BishopFox/sliver#221]
Hello lovely guys!
Recently I saw the tcp pivot option and it is very exciting! 
But, I didn't find wiki on this.
Can you please explain how to use it?

Thanks!

Ilansec

**Comment by rkervella** [comment]
Hi @Ilan-sec.
You're right, we're still lacking some documentation related to pivots (both TCP and SMB).
To get you started here's a simple example.

From a sliver session, you can create what we call a "pivot listener" on the target system. To do that, just use either the `tcp-pivot` or `named-pipe` commands. Here are some examples:

```
sliver (CHUBBY_PAVILION) > tcp-pivot -l 8000 -s 172.16.241.1
[*] Listening on tcp://172.16.241.1:8000
...
sliver (DELIGHTFUL_TELLER) > named-pipe -n lol
[*] Listening on \\.\pipe\lol
```

Once these listeners are started, you can generate a sliver (or create a profile) using either `--tcp-pivot` or `--named-pipe` as transports, instead of the traditional `--http`, `--mtls` or `--dns` flags:

```bash
# generate a new profile for a sliver shellcode that will connect using a TCP pivot
sliver > new-profile --name pivot-shellcode --skip-symbols --tcp-pivot 172.16.241.1:8000 --format shellcode
# generate a new sliver executable that will connect other a SMB named pipe pivot
sliver > generate --skip-symbols --named-pipe desk01.centrallab.local/.pipe/lol
```

I'll keep this issue opened until we have some docs on the wiki about that.

**Comment by rkervella** [comment]
Alright, I've put up some docs [in the wiki](https://github.com/BishopFox/sliver/wiki/Pivots).

Please reopen this issue if you see something missing.

**Comment by Ilan-sec** [comment]
Well Ronan, you are so the BEST!!!!
I have no other words to describe you.
Great thanks!!!

Ilan-sec.

בתאריך יום ה׳, 9 ביולי 2020, 11:32, מאת Ronan Kervella ‏<
notifications@github.com>:
