### ISSUE TITLE
No MainDLL execution option

### ISSUE THREAD

**Issue by Ilan-sec** [BishopFox/sliver#234]
Hello dear guys,
As I tried to use the dll file for starting a shell, it worked only with RunSliver entry point but not as is (main_dll function). It can be very helpful to add this option to abuse dll hijacking issues. Is that a change you can do or am I missed something?

Thanks,

Ilan-Sec.

**Comment by rkervella** [comment]
The reason it's been that way is because so far it messes things up when we use command that inject a Sliver shellcode. There's some race condition due to how sRDI works, and basically we either get 2 Sliver sessions when using things like `migrate` or `getsystem`, or no session at all.

To change it, you can uncomment [this line](https://github.com/BishopFox/sliver/blob/master/sliver/sliver.c#L23).

I need to work on a better fix when I get some time.

**Comment by Ilan-sec** [comment]
Thanks for your quick response!
I tried it but after compiling, running sliver and generate command the all
app falls down,

‫בתאריך יום ב׳, 10 באוג׳ 2020 ב-21:40 מאת ‪Ronan Kervella‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by lesnuages** [comment]
Hm that is weird. How do you test exactly?

**Comment by Ilan-sec** [comment]
Uncomment the 23 line, compiling with make static-linux, fire up the app,
generate --mtls ip . It gives the lines of generating but takes down the
app imidetly.

בתאריך יום ב׳, 10 באוג׳ 2020, 23:17, מאת Ronan Kervella ‏<
notifications@github.com>:

**Comment by lesnuages** [comment]
How you mean it doesn't compile?

**Comment by Ilan-sec** [comment]
I didn't say it dosen't compile, it is. I just said it goes down after
trying to generate. Btw, I don't know for sure it is because the uncomment.
Maybe I have another problem. Most of the time I'm using a pre compiled
release.

בתאריך יום ב׳, 10 באוג׳ 2020, 23:40, מאת Ronan Kervella ‏<
notifications@github.com>:

**Comment by lesnuages** [comment]
Please make sure you followed all of these steps: https://github.com/BishopFox/sliver/wiki/Compile-From-Source
