### ISSUE TITLE
Client Keep Alives for mTLS Connections

### ISSUE THREAD

**Issue by Matir** [BishopFox/sliver#311]
**Is your feature request related to a problem? Please describe.**
If the Sliver server (or an intermediate proxy) loses its connection states, the Sliver implant does not notice until the connection returns EOF.  This will not happen if no traffic is flowing because the socket will not get a RST until a packet is sent.

**Describe the solution you'd like**
Adding client-side keepalives to the TCP Socket used for mTLS would allow the client to notice the connection has failed.

**Describe alternatives you've considered**
Protocol level keepalives.  Seems silly, but I considered it!

I'm happy to send a PR with a proposed implementation if this makes sense.

**Comment by moloch--** [comment]
Honestly, I think the easiest way to implement this is with the existing `ping` command and calling it on an interval from the server for mTLS sessions --I've also thought about implementing something like this, as mTLS connections are also marked as "DEAD" when they're not since no message has been sent/recv'd even though the underlying TCP connection is still open.

The advantage of using the server to call `ping` is that we can adjust the intervals without needing to recompile/reconfig the implant.

**Comment by moloch--** [comment]
Oh wait, we need the client to detect the failure, should've read closer, yea makes sense to implement it on the client/implant-side.

Though we may want to do it from both ends if no message has been received on a certain interval, that way both can detect the connection has died.

**Comment by moloch--** [comment]
Fixed in `stage`
