### ISSUE TITLE
Multiplayer list players offline

### ISSUE THREAD

**Issue by scaery** [BishopFox/sliver#333]
**Describe the bug**
Seems if enabled multiplayer mode in latest Sliver 1.3.0 the players never show up as online.

**To Reproduce**
1. start `./sliver-server`
2. generate two new-players
```
new-player --operator hacker01 --lhost a.b.c.d --lport 31337
new-player --operator hacker02 --lhost a.b.c.d --lport 31337
```
3. enable `multiplayer` on
4. connect with `./sliver-client -import bla.json` from different workstations
5. check output of `players` (you will see that e.g. player1 and player2 coming online in the console, but the players command does not show them as online)

**Expected behavior**
Show online players in multiplayer setup when connected and interacting in sessions.

**Desktop (please complete the following information):**
 - OS: [Kali Linux]

**Additional context**
Does anyone else encountering this problem when having a multiplayer setup? I am using multiplayer mode because if a pipe drops or get stucked/timouts I simply can press ctl+c and restart the client. Its kind of useful to me but less documented.

**Comment by rkervella** [comment]
Looks like a missing implementation:

https://github.com/BishopFox/sliver/blob/f9d4f5e79d0f0abd84a626ad5a4bca02e648457f/server/rpc/rpc-operators.go#L45-L56

The `isPlayerOnline()` function is called, but since it's commented out, it doesn't display anything. It should be an easy fix, unless I'm missing some context about why this function was commented out in the first place. @moloch-- any input on that one?

**Comment by moloch--** [comment]
haha sorry, I never went back and fixed this after the port to grpc. In my defense since grpc uses multiple underlying TCP connections detecting online players isn't as trivial as it was in the old design.

**Comment by moloch--** [comment]
@rkervella Yea it's not that easy to fix, but I have a few ideas on how we can do it.

**Comment by moloch--** [comment]
Fixed in `stage`
