### ISSUE TITLE
https sliver fails to fetch public key

### ISSUE THREAD

**Issue by moj0-bf** [BishopFox/sliver#60]
**Debug:**
```
2019/04/19 16:19:01 sliver.go:37: Hello my name is BUSY_PNEUMONIA
2019/04/19 16:19:01 limits_windows.go:21: IsDebuggerPresent = 0
2019/04/19 16:19:01 limits.go:32: Limit checks completed
2019/04/19 16:19:01 transports.go:117: Starting connection loop ...
2019/04/19 16:19:01 transports.go:128: Next CC = https://142.93.153.170
2019/04/19 16:19:01 transports.go:216: Connecting -> http(s)://142.93.153.170
2019/04/19 16:19:01 tcp-http.go:113: [http] GET -> https://142.93.153.170/sample/sample.txt
2019/04/19 16:19:01 tcp-http.go:119: [http] Failed to fetch server public key: Get https://142.93.153.170/sample/sample.txt: x509: certificate signed by unknown authority
2019/04/19 16:19:01 tcp-http.go:81: Invalid public key
```
If you start an http listener as well, the payload eventually falls back to http and connects

**Comment by clhefton** [comment]
I have a question on this because I'm getting the same error. Is the config generated for a listener supposed to use the cert the listener is using for the "website"? The cert is trusted but when I look at the config generated, it's using some random cert for `ca_certificate`. 

Listener was started with `https --website website-name --domain mydomain.com -c cert.pem -k privkey.pem`. 
Player created with `new-player --lhost mydomain.com --lport 443 --operator someName`

I'm getting the same error `x509: certificate signed by unknown authority`

**Comment by clhefton** [comment]
I'm using the release, by the way. I didn't build from source. I was just wondering if there's a quick fix without re-building infrastructure.

**Comment by clhefton** [comment]
Nevermind, I answered my own question. I changed the client ca_certificate to the one I told the https listener to use and it worked
