### ISSUE TITLE
It will get stuck when entering the shell

### ISSUE THREAD

**Issue by fadm218** [BishopFox/sliver#717]
When the server enters too many shells, the next time you enter the shell, the shell will be stuck and you will not be able to enter. You can only restart the server to enter again.

<img width="814" alt="image" src="https://user-images.githubusercontent.com/104477138/173982141-fd0e2453-b962-4c3a-bedd-04bc9cf8a0aa.png">

**Comment by moloch--** [comment]
Can you provide more information on the number of shells and operating system, is there anything in the logs?

**Comment by hayasec** [comment]
same problem. 
Now reboot server can solve it.

**Comment by moloch--** [comment]
I still need more information about the setup/configuration/operating system to help.

**Comment by rkervella** [comment]
There an unexpected behavior in the `tun_handlers`: most of them like `shell` don't return anything since they're called like this:

https://github.com/BishopFox/sliver/blob/0c7c2e0291a1ceca84ac64917d4c33111dce3b8e/implant/sliver/sliver.go#L595-L599

We don't handle the case when the handler fails, which happens for shell when you try to use it with `make-token` for example. We should have a way to send back the errors to the server so we can gracefully close the tunnel / prevent from opening it in the first place.

**Comment by rkervella** [comment]
Just pushed #725 which should fix some of these cases. Not sure if it's the issue here though, since the sub process is properly spawned, the issue might lie elsewhere. @hayasec as @moloch-- said, we need more information about your environment to be able to reproduce. Please follow the issue template, it's here for a reason, otherwise you're just making it harder for us to fix things.
